title: Roger Hu # your name (or website title) here
logo: "/images/logo.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  I'm a self-taught data scientist with 7 years of quantative and financial modeling experience as a consultant and a manager at Deloitte. <br>
  You can find me on <a href="https://www.linkedin.com/in/rogerhu1989/">LinkedIn</a> or email me <a href="mailto:rogerhu1989
  @gmail.com">here</a>."
  <br>
  <a href="https://drive.google.com/file/d/1klcZfZBzOthtPWuMIvfK7lQjH6anMa3x/view?usp=sharing">View My Resume</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-173737942-1 # your Google Analytics tracking ID here
