title: Roger Hu # your name (or website title) here
logo: "/images/logo.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  After doing data munging and financial modeling for mlutinational corporation clients at Deloitte for 7 years as an analyst, senior consultant, and manager, I took the risk and challenge to make a career change to become a data analyst by teaching myself to conduct more complex and larger scale data analysis in Python and R. 
  <br><br>
   
  <a href="https://www.linkedin.com/in/rogerhu1989/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://drive.google.com/file/d/1klcZfZBzOthtPWuMIvfK7lQjH6anMa3x/view?usp=sharing">View My Resume</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-173737942-1 # your Google Analytics tracking ID here
